<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>

	<Authors>Nuno ARAUJO</Authors>
	<Description>Flow.Ingoing is a .NET library that simplifies API integration by providing a flexible and configurable way to process API flows</Description>

	<PackageReadmeFile>..\README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/NunoTek/Flow.Ingoing</RepositoryUrl>
	<RepositoryType>git</RepositoryType>

	<EnablePackageValidation>true</EnablePackageValidation>
	<!-- Optional: Detect breaking changes from a previous version -->
	 <PackageValidationBaselineVersion>1.0.0</PackageValidationBaselineVersion> 
  </PropertyGroup>

  <ItemGroup>
	<None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Polly" Version="8.6.5" />
  </ItemGroup>

</Project>
